# Generated by Django 5.2.4 on 2025-07-17 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcarrito',
            old_name='agregado_el',
            new_name='agregado_en',
        ),
    ]
