# Generated by Django 5.2.4 on 2025-07-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=8)),
                ('categoria', models.CharField(choices=[('recarga', 'Recarga'), ('pack', 'Pack Inicial'), ('basico', 'Dispensador Básico'), ('electrico', 'Dispensador Eléctrico')], max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
