# Generated by Django 5.2.4 on 2025-11-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('recargas', 'Recargas'), ('dispensadores', 'Dispensadores'), ('accesorios', 'Accesorios'), ('Promociones', 'Pack Inicial')], max_length=20),
        ),
    ]
